"""One-off helper to emit ``source_registry.json`` (run from repo root if entries need bulk edits)."""

from __future__ import annotations

import json
from pathlib import Path

PAGE_REQ = "PAGE_REQUIRED_DO_NOT_RELEASE"


def _e(
    source_key: str,
    *,
    authors: str,
    year: int | None,
    title: str,
    publication_or_book: str,
    publisher: str | None,
    edition: str | None,
    volume: str | None,
    issue: str | None,
    article_pages: str | None,
    doi_or_url: str | None,
    local_private_filename: str,
    pages_consulted: str,
    evidence_type: str,
    reliability_level: str,
    used_for: str,
    notes: str,
    no_long_quotes: bool = True,
    short_quote_optional: str | None = None,
) -> dict:
    return {
        "source_key": source_key,
        "authors": authors,
        "year": year,
        "title": title,
        "publication_or_book": publication_or_book,
        "publisher": publisher,
        "edition": edition,
        "volume": volume,
        "issue": issue,
        "article_pages": article_pages,
        "doi_or_url": doi_or_url,
        "local_private_filename": local_private_filename,
        "pages_consulted": pages_consulted,
        "evidence_type": evidence_type,
        "reliability_level": reliability_level,
        "used_for": used_for,
        "notes": notes,
        "short_quote_optional": short_quote_optional,
        "no_long_quotes": no_long_quotes,
    }


def build_entries() -> list[dict]:
    """Bibliographic facts taken from public indexes where noted; else paraphrase + PAGE_REQ."""
    return [
        _e(
            "sivian_dunn_white_1931_absolute_amplitudes_spectra",
            authors="Sivian, L. J.; Dunn, H. K.; White, S. D.",
            year=1931,
            title="Absolute Amplitudes and Spectra of Certain Musical Instruments and Orchestras",
            publication_or_book="The Journal of the Acoustical Society of America",
            publisher="Acoustical Society of America (AIP Publishing)",
            edition=None,
            volume="2",
            issue="3",
            article_pages="330-371",
            doi_or_url="https://doi.org/10.1121/1.1915260",
            local_private_filename="ABSOLUTE AMPLITUDES AND SPECTRA OF CERTAIN MUSICAL INSTRUMENTS AND ORCHESTRAS.pdf",
            pages_consulted="330-371 (journal pagination; verify scan numbering before citing as PDF page numbers)",
            evidence_type="measured_acoustic_data",
            reliability_level="high",
            used_for="Early orchestral and instrument absolute spectra / levels; contextualizes fixed spectral heuristics.",
            notes="Paraphrase: foundational measured spectra and amplitudes for several instruments and orchestral passages. "
            "Use for literature context for orchestral spectra, not as a substitute for audio analysis in this codebase.",
            short_quote_optional=None,
        ),
        _e(
            "physical_correlates_brass_instrument_tones_pending",
            authors="Unverified from this repository (open private PDF title page to curate).",
            year=None,
            title="Physical Correlates of Brass-Instrument Tones",
            publication_or_book="Peer-reviewed article (venue to be confirmed from document)",
            publisher=None,
            edition=None,
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="Physical Correlates of Brass-Instrument Tones.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="musical_instrument_acoustics",
            reliability_level="low",
            used_for="Brass timbre / radiated spectrum correlates (planned acoustic-h proxy layer).",
            notes="Year not verified. Filename suggests brass tone correlates; do not cite page numbers until verified on the held copy.",
        ),
        _e(
            "campbell_gilbert_myers_2021_science_of_brass_instruments",
            authors="Campbell, Murray; Gilbert, Joël; Myers, Arnold",
            year=2021,
            title="The Science of Brass Instruments",
            publication_or_book="Springer Nature (Modern Acoustics and Signal Processing)",
            publisher="Springer",
            edition="1",
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url="https://doi.org/10.1007/978-3-030-55686-0",
            local_private_filename="Campbel, Murray_The Science of Brass Instruments.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="musical_instrument_acoustics",
            reliability_level="high",
            used_for="Brass bore, radiation, and timbre science for orchestration-informed heuristics.",
            notes="Working filename shows spelling 'Campbel'; verify against printed title page. Edition metadata from public publisher record.",
        ),
        _e(
            "meyer_acoustics_performance_of_music",
            authors="Meyer, Jürgen",
            year=2009,
            title="Acoustics and the Performance of Music",
            publication_or_book="Book (English-language reference edition; verify imprint against held copy)",
            publisher="Springer / Focal (imprint varies by edition; verify)",
            edition="Verify against held copy",
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="IMP_Acoustics and the Performance of music_(Jürgen Meyer) (z-lib.org).pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="orchestration_performance_acoustics",
            reliability_level="medium",
            used_for="Room-orchestra balance, dynamic strength, and performance acoustics context.",
            notes="Year/edition paraphrased from widely catalogued English editions; confirm exact imprint on private copy. "
            "Not used at runtime.",
        ),
        _e(
            "fletcher_rossing_1998_physics_of_musical_instruments",
            authors="Fletcher, Neville H.; Rossing, Thomas D.",
            year=1998,
            title="The Physics of Musical Instruments",
            publication_or_book="Springer-Verlag New York (2nd ed. commonly catalogued)",
            publisher="Springer",
            edition="2",
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url="https://doi.org/10.1007/978-0-387-21603-4",
            local_private_filename="The_Physics_of_Musical_Instruments.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="theoretical_acoustics",
            reliability_level="high",
            used_for="Resonator models, string/wind/brass principles for high-level acoustic proxies.",
            notes="Paraphrase: standard reference for linear and nonlinear oscillators in musical instruments. "
            "PDF page numbers not verified in this registry.",
        ),
        _e(
            "rossing_2010_science_of_string_instruments",
            authors="Rossing, Thomas D. (editor); multiple contributors",
            year=2010,
            title="The Science of String Instruments",
            publication_or_book="Springer Science+Business Media",
            publisher="Springer",
            edition="1",
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url="https://doi.org/10.1007/978-1-4419-7110-4",
            local_private_filename="Thomas D. Rossing_The Science of String Instruments.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="musical_instrument_acoustics",
            reliability_level="high",
            used_for="Bow-string spectra, body modes, and timbre for string-family heuristics.",
            notes="Paraphrase: edited survey of string-instrument acoustics. Confirm pagination on held scan before citing pages.",
        ),
        _e(
            "rossing_et_al_science_of_sound_pearson",
            authors="Rossing, Thomas D.; Wheeler, Paul A.; Fahy, Frank (editions vary)",
            year=2014,
            title="Science of Sound (Pearson international edition; title varies by printing)",
            publication_or_book="Pearson Education (international editions catalogued under similar titles)",
            publisher="Pearson",
            edition="Verify printing (e.g., 4th or New International Edition)",
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="IMP_The-Science-of-Sound-Pearson-New-International-Edition-by-Thomas-1.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="psychoacoustics",
            reliability_level="medium",
            used_for="Psychoacoustics fundamentals (loudness, pitch, timbre descriptors) for fusion documentation.",
            notes="Edition line paraphrased from common Pearson listings; verify table of contents on private PDF.",
        ),
        _e(
            "benade_1976_fundamentals_musical_acoustics",
            authors="Benade, Arthur H.",
            year=1976,
            title="Fundamentals of Musical Acoustics",
            publication_or_book="Oxford University Press",
            publisher="Oxford University Press",
            edition="1",
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="Fundamentals of Musical Acoustics -- Benade.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="musical_instrument_acoustics",
            reliability_level="high",
            used_for="Woodwind air column modes, clarinet-like odd-harmonic behavior, brass lip reed basics.",
            notes="Paraphrase: canonical pedagogical reference for musical instrument acoustics. PDF page map not verified here.",
        ),
        _e(
            "analysis_musical_instrument_tones_pending",
            authors="Unverified (see PDF title page).",
            year=None,
            title="Analysis of Musical Instrument Tones (exact title per document)",
            publication_or_book="Article or chapter (venue pending curation)",
            publisher=None,
            edition=None,
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="IMP_Analysis of Musical Instrument Tones.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="signal_analysis",
            reliability_level="low",
            used_for="Instrument tone analysis / spectral envelope methods (literature trail).",
            notes="Year not verified. Curate DOI and pagination from the private scan.",
        ),
        _e(
            "campbell_acoustics_musical_instruments_pending",
            authors="Campbell, M. (initials/affiliation unverified in registry)",
            year=None,
            title="Acoustics of Musical Instruments (exact title per document)",
            publication_or_book="Monograph or proceedings (verify imprint)",
            publisher=None,
            edition=None,
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="IMP_CAMPBELL-M-Acoustics-of-Musical-Instruments.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="musical_instrument_acoustics",
            reliability_level="low",
            used_for="General instrument acoustics cross-checks for taxonomy and timbre proxies.",
            notes="Year not verified. Filename suggests Murray Campbell-related material; confirm bibliographic record.",
        ),
        _e(
            "discrimination_musical_instrument_sounds_pending",
            authors="Unverified (see PDF title page).",
            year=None,
            title="Discrimination of musical instrument sounds (exact title per document)",
            publication_or_book="Peer-reviewed article (venue pending)",
            publisher=None,
            edition=None,
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="IMP_Discrimination of musical instrument sounds r.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="psychoacoustics",
            reliability_level="low",
            used_for="Listening discrimination / similarity cues relevant to fusion weighting literature.",
            notes="Year not verified.",
        ),
        _e(
            "fixed_average_spectra_orchestral_instrument_tones_pending",
            authors="Unverified (see PDF title page).",
            year=None,
            title="Fixed Average Spectra of Orchestral Instrument Tones",
            publication_or_book="Peer-reviewed article (venue pending)",
            publisher=None,
            edition=None,
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="IMP_Fixed Average Spectra of Orchestral Instrument Tones.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="measured_acoustic_data",
            reliability_level="medium",
            used_for="Orchestral instrument long-term average spectra (context for static heuristic tables).",
            notes="Year not verified.",
        ),
        _e(
            "sound_power_timbre_dynamic_strength_orchestral_pending",
            authors="Unverified (see PDF title page).",
            year=None,
            title="Sound power and timbre as cues for the dynamic strength of orchestral instruments",
            publication_or_book="Peer-reviewed article (venue pending)",
            publisher=None,
            edition=None,
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="IMP_Sound power and timbre as cues for the dynamic strength of orchestral instruments.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="orchestration_performance_acoustics",
            reliability_level="medium",
            used_for="Linking timbral cues to perceived dynamic strength in orchestral texture.",
            notes="Year not verified.",
        ),
        _e(
            "statistical_analysis_musical_instruments_pending",
            authors="Unverified (see PDF title page).",
            year=None,
            title="Statistical Analysis of Musical Instruments (exact title per document)",
            publication_or_book="Article or report (venue pending)",
            publisher=None,
            edition=None,
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="IMPPPP_Statistical Analysis of Musical Instruments.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="signal_analysis",
            reliability_level="low",
            used_for="Statistical spectral models for instrument families.",
            notes="Year not verified.",
        ),
        _e(
            "index_relative_quality_musical_instruments_pending",
            authors="Unverified (see PDF title page).",
            year=None,
            title="Index for the Relative Quality among Musical Instruments",
            publication_or_book="Unknown venue (curate from document)",
            publisher=None,
            edition=None,
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="Index for the Relative Quality among Musical Instruments.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="instrument_classification",
            reliability_level="low",
            used_for="Historical / qualitative ranking context (not used in formulas).",
            notes="Year not verified.",
        ),
        _e(
            "musical_instrument_timbres_classification_spectral_pending",
            authors="Unverified (see PDF title page).",
            year=None,
            title="Musical Instrument Timbres Classification with Spectral Features",
            publication_or_book="Conference or journal (pending)",
            publisher=None,
            edition=None,
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="Musical Instrument Timbres Classification with Spectral Features.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="instrument_classification",
            reliability_level="medium",
            used_for="MFCC / spectral-feature classifiers as literature context for future acoustic_heuristic mode.",
            notes="Year not verified.",
        ),
        _e(
            "musical_instrument_classification_higher_order_spectra_pending",
            authors="Unverified (see PDF title page).",
            year=None,
            title="Musical instrument classification using higher order spectra",
            publication_or_book="Conference or journal (pending)",
            publisher=None,
            edition=None,
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="Musical_instrument_classification_using_higher_order_spectra.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="instrument_classification",
            reliability_level="medium",
            used_for="Higher-order spectral features for classification (literature trail).",
            notes="Year not verified.",
        ),
        _e(
            "relevance_spectral_features_instrument_classification_pending",
            authors="Unverified (see PDF title page).",
            year=None,
            title="On the relevance of spectral features for instrument classification",
            publication_or_book="Conference or journal (pending)",
            publisher=None,
            edition=None,
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="On the relevance of spectral features for instrument classification.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="spectral_features",
            reliability_level="medium",
            used_for="Feature relevance for classifier design (documentation only).",
            notes="Year not verified.",
        ),
        _e(
            "science_percussion_instruments_pending",
            authors="Unverified (see PDF title page).",
            year=None,
            title="Science of Percussion Instruments",
            publication_or_book="Book or monograph (pending)",
            publisher=None,
            edition=None,
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="Science of Percussion Instruments.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="musical_instrument_acoustics",
            reliability_level="medium",
            used_for="Percussion timbre and bar/membrane modes for ontology notes.",
            notes="Year not verified.",
        ),
        _e(
            "sound_production_double_reed_pending",
            authors="Unverified (see PDF title page).",
            year=None,
            title="Sound Production Analysis of a Double Reed Instrument",
            publication_or_book="Thesis or article (pending)",
            publisher=None,
            edition=None,
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="Sound_Production_Analysis_of_a_Double_Reed_Instrument.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="musical_instrument_acoustics",
            reliability_level="low",
            used_for="Double-reed excitation and spectrum context.",
            notes="Year not verified.",
        ),
        _e(
            "statistical_study_spectral_parameters_pending",
            authors="Unverified (see PDF title page).",
            year=None,
            title="Statistical study of spectral parameters in musical instrument (full title per PDF)",
            publication_or_book="Peer-reviewed article (pending)",
            publisher=None,
            edition=None,
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="Statistical study of spectral parameters in musical instrument.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="spectral_features",
            reliability_level="low",
            used_for="Distributions of spectral parameters across instruments.",
            notes="Year not verified.",
        ),
        _e(
            "clarinet_spectrum_theory_experiment_pending",
            authors="Unverified (see PDF title page).",
            year=None,
            title="The clarinet spectrum: theory and experiment (punctuation per PDF)",
            publication_or_book="Peer-reviewed article (pending)",
            publisher=None,
            edition=None,
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="The clarinet spectrum Theory and experiment.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="musical_instrument_acoustics",
            reliability_level="medium",
            used_for="Clarinet odd-harmonic / cutoff literature for clarinet pairwise heuristics.",
            notes="Year not verified.",
        ),
        _e(
            "tonal_spectra_wind_instruments_pending",
            authors="Unverified (see PDF title page).",
            year=None,
            title="Tonal Spectra of Wind Instruments",
            publication_or_book="Peer-reviewed article (pending)",
            publisher=None,
            edition=None,
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="Tonal Spectra of Wind Instruments.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="measured_acoustic_data",
            reliability_level="medium",
            used_for="Wind-instrument steady-state spectra references.",
            notes="Year not verified.",
        ),
        _e(
            "viola_tonnerre_pending",
            authors="Unverified (see PDF title page).",
            year=None,
            title="Viola Tonnerre (exact title per PDF)",
            publication_or_book="Unknown venue (likely French-language; pending)",
            publisher=None,
            edition=None,
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="Viola_Tonnerre.pdf",
            pages_consulted=PAGE_REQ,
            evidence_type="musical_instrument_acoustics",
            reliability_level="low",
            used_for="Viola-specific acoustics or repertoire context if curated.",
            notes="Year not verified.",
        ),
        _e(
            "homogeneity_analyser_timbral_fusion_evidence_stub",
            authors="Timbral Instrumental Homogeneity project",
            year=2026,
            title="Internal evidence map for symbolic timbral and planned fusion layers",
            publication_or_book="Project documentation (this repository)",
            publisher=None,
            edition=None,
            volume=None,
            issue=None,
            article_pages=None,
            doi_or_url=None,
            local_private_filename="",
            pages_consulted="N/A (project documentation; no private PDF)",
            evidence_type="project_specific",
            reliability_level="medium",
            used_for="Tracks which registry keys will bind to future acoustic_heuristic / fusion configuration.",
            notes="Paraphrase: placeholder entry satisfying project_specific evidence; not a peer-reviewed acoustic measurement.",
            short_quote_optional=None,
        ),
    ]


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    out = root / "src" / "homogeneity_analyser" / "acoustic_profiles" / "source_registry.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    data = build_entries()
    out.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {len(data)} entries to {out}")


if __name__ == "__main__":
    main()
