"""H_TI CSV/JSON export column registries and row serialization."""

from __future__ import annotations

import json
from typing import Any

from homogeneity_analyser.analyzers.symbolic_blend_layers import (
    HTI_SYMBOLIC_BLEND_CSV_JSON_DICT_KEYS,
    HTI_SYMBOLIC_BLEND_SERIES_KEYS,
)
from homogeneity_analyser.analyzers.timbral_acoustic_proxy import (
    HTI_ACOUSTIC_PROXY_CSV_JSON_DICT_KEYS,
    HTI_ACOUSTIC_PROXY_SERIES_KEYS,
)


def hti_csv_row_dict(row: dict[str, Any]) -> dict[str, Any]:
    out = dict(row)
    for k in (
        "technique_state_distribution",
        "instrument_distribution",
        "family_distribution",
        "macrofamily_distribution",
        "instrumental_subfamily_distribution",
        "notated_dynamic_level_distribution",
        "active_weights",
        *HTI_SYMBOLIC_BLEND_CSV_JSON_DICT_KEYS,
        *HTI_ACOUSTIC_PROXY_CSV_JSON_DICT_KEYS,
    ):
        v = out.get(k)
        if isinstance(v, dict):
            out[k] = json.dumps(v, sort_keys=True, ensure_ascii=False)
    for k in (
        "dominant_instruments",
        "dominant_macrofamilies",
        "dominant_families",
        "dominant_timbral_states",
        "dominant_dynamics",
    ):
        v = out.get(k)
        if isinstance(v, list):
            out[k] = json.dumps(v, ensure_ascii=False)
    return out


HTI_CSV_COLUMNS: tuple[str, ...] = tuple(
    [
        "t_quarterLength",
        "window_start",
        "window_end",
        "edge_window",
        "window_coverage_ratio",
        "measure",
        "pitch_interpretation_mode",
        "H_TI",
        "H_TI_core",
        "H_TI_strict",
        "H_TI_subfamily_relieved",
        "same_subfamily_relief_factor",
        "instrument_effective_uniformity",
        "instrument_uniformity",
        "instrumental_subfamily_uniformity",
        "macrofamily_uniformity",
        "technique_uniformity",
        "register_proximity",
        "register_compactness",
        "register_span_proximity",
        "register_span_factor",
        "pairwise_interval_proximity",
        "register_pair_distance_factor",
        "pairwise_interval_coverage_status",
        "n_instruments",
        "n_families",
        "n_macrofamilies",
        "register_span_semitones",
        "dominant_instrument",
        "dominant_instruments",
        "dominant_instrument_tie",
        "dominant_instrument_share",
        "dominant_instrument_margin",
        "dominant_instrumental_subfamily",
        "dominant_macrofamily",
        "dominant_macrofamilies",
        "dominant_macrofamily_tie",
        "dominant_macrofamily_share",
        "dominant_macrofamily_margin",
        "dominant_family",
        "dominant_families",
        "dominant_family_tie",
        "dominant_family_share",
        "dominant_family_margin",
        "dominant_timbral_state",
        "dominant_timbral_states",
        "dominant_timbral_state_tie",
        "dominant_timbral_state_share",
        "dominant_timbral_state_margin",
        "technique_state_distribution",
        "instrument_distribution",
        "family_distribution",
        "macrofamily_distribution",
        "technique_coverage_status",
        "register_coverage_status",
        "notated_dynamic_coherence",
        "dominant_dynamic",
        "dominant_dynamics",
        "dominant_dynamic_tie",
        "dominant_dynamic_share",
        "dominant_dynamic_margin",
        "dynamic_intensity_ordinal",
        "dynamic_softness",
        "dynamic_coverage_status",
        "crescendo_active",
        "diminuendo_active",
        "dynamic_divergence_detected",
        "notated_dynamic_level_distribution",
        "soft_blend_potential",
        "intra_family_convergence_potential",
        "transparent_blend_potential",
        "bright_salience_risk",
        "projection_divergence_risk",
        "masked_tonal_mass_risk",
        "same_family_mixed_instrument_mass",
        "family_heterogeneity",
        "masking_context_weight",
        "family_specific_projection_weight",
        "dynamic_interpretation_label",
        "dynamic_interpretation_label_subfamily_relieved",
        "dynamic_evidence_status",
        "H_TI_affinity_literature_relieved",
        "timbral_affinity_uniformity",
        "instrument_affinity_effective_uniformity",
        "timbral_affinity_profile",
        "timbral_affinity_relief_factor",
        "timbral_affinity_dynamic_factor",
        "timbral_affinity_dynamic_status",
        "affinity_dynamic_interpretation_label",
        "H_TI_affinity_dynamic_conditioned",
        "timbral_affinity_evidence_status",
        "timbral_affinity_rule_summary",
        "timbral_affinity_literature_sources",
        "literature_affinity_unverified_rule_blocked",
        *HTI_SYMBOLIC_BLEND_SERIES_KEYS,
        *HTI_ACOUSTIC_PROXY_SERIES_KEYS,
    ]
)

# Keys stored per window by ``analyze_hti`` (used by JSON export).
HTI_EXPORT_TIME_SERIES_KEYS: tuple[str, ...] = tuple(
    k
    for k in (
        "t",
        "window_start",
        "window_end",
        "edge_window",
        "window_coverage_ratio",
        "effective_window_overlap_duration",
        "measure",
        "pitch_interpretation_mode",
        "H_TI",
        "H_TI_core",
        "H_TI_strict",
        "H_TI_subfamily_relieved",
        "same_subfamily_relief_factor",
        "instrument_effective_uniformity",
        "instrument_uniformity",
        "instrumental_subfamily_uniformity",
        "macrofamily_uniformity",
        "family_uniformity",
        "technique_uniformity",
        "register_proximity",
        "register_compactness",
        "register_span_proximity",
        "register_span_factor",
        "pairwise_interval_proximity",
        "register_pair_distance_factor",
        "pairwise_interval_coverage_status",
        "n_instruments",
        "n_families",
        "n_macrofamilies",
        "register_span_semitones",
        "dominant_instrument",
        "dominant_instruments",
        "dominant_instrument_tie",
        "dominant_instrument_share",
        "dominant_instrument_margin",
        "dominant_instrumental_subfamily",
        "dominant_macrofamily",
        "dominant_macrofamilies",
        "dominant_macrofamily_tie",
        "dominant_macrofamily_share",
        "dominant_macrofamily_margin",
        "dominant_family",
        "dominant_families",
        "dominant_family_tie",
        "dominant_family_share",
        "dominant_family_margin",
        "dominant_timbral_state",
        "dominant_timbral_states",
        "dominant_timbral_state_tie",
        "dominant_timbral_state_share",
        "dominant_timbral_state_margin",
        "technique_state_distribution",
        "instrument_distribution",
        "family_distribution",
        "macrofamily_distribution",
        "technique_coverage_status",
        "register_coverage_status",
        "active_weights",
        "notated_dynamic_level_distribution",
        "notated_dynamic_coherence",
        "dominant_dynamic",
        "dominant_dynamics",
        "dominant_dynamic_tie",
        "dominant_dynamic_share",
        "dominant_dynamic_margin",
        "dynamic_intensity_ordinal",
        "dynamic_softness",
        "dynamic_coverage_status",
        "crescendo_active",
        "diminuendo_active",
        "dynamic_divergence_detected",
        "soft_blend_potential",
        "intra_family_convergence_potential",
        "transparent_blend_potential",
        "bright_salience_risk",
        "projection_divergence_risk",
        "masked_tonal_mass_risk",
        "same_family_mixed_instrument_mass",
        "family_heterogeneity",
        "masking_context_weight",
        "family_specific_projection_weight",
        "dynamic_interpretation_label",
        "dynamic_interpretation_label_subfamily_relieved",
        "dynamic_evidence_status",
        "H_TI_affinity_literature_relieved",
        "timbral_affinity_uniformity",
        "instrument_affinity_effective_uniformity",
        "timbral_affinity_profile",
        "timbral_affinity_relief_factor",
        "timbral_affinity_dynamic_factor",
        "timbral_affinity_dynamic_status",
        "affinity_dynamic_interpretation_label",
        "H_TI_affinity_dynamic_conditioned",
        "timbral_affinity_evidence_status",
        "timbral_affinity_rule_summary",
        "timbral_affinity_literature_sources",
        "literature_affinity_unverified_rule_blocked",
        *HTI_SYMBOLIC_BLEND_SERIES_KEYS,
        *HTI_ACOUSTIC_PROXY_SERIES_KEYS,
    )
)
